In [130]:
%run 01_initialization.ipynb
df=df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64
 2   Age     4 non-null      int64
 3   CGPA    4 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 260.0+ bytes

In [131]:
df

      Name  Roll  Age  CGPA
0  Monirul  3982   24  3.99
1    Sayem  2981   25  4.00
2   Hafiza  3973   22  3.87
3      Mim  2973   21  2.78

In [132]:
# Adding Column at the end
# df["Column_Name"] = [Values]

df['Phone']=['0123456789', '0123456789', '0123456789', '0123456789']

In [133]:
df

      Name  Roll  Age  CGPA       Phone
0  Monirul  3982   24  3.99  0123456789
1    Sayem  2981   25  4.00  0123456789
2   Hafiza  3973   22  3.87  0123456789
3      Mim  2973   21  2.78  0123456789

In [134]:
# Adding Column at the middle
# df.insert(column_index, column_name, values)

df.insert(3, 'Batch', ['A', 'B', 'C', 'D'])

In [135]:
df

      Name  Roll  Age Batch  CGPA       Phone
0  Monirul  3982   24     A  3.99  0123456789
1    Sayem  2981   25     B  4.00  0123456789
2   Hafiza  3973   22     C  3.87  0123456789
3      Mim  2973   21     D  2.78  0123456789

In [136]:
# Add new rows

In [137]:
new_row1 = {
    'Name' : "Sayem",
    'Roll' : 2981,
    'Age' : 25,
    'Batch' : 'B',
    'CGPA' : 4.00,
    'Phone' : '0123456789'
}

new_row2 = {
    'Name' : "Alice",
    'Roll' : 2985,
    'Age' : 23,
    'Batch' : 'C',
    'CGPA' : 3.70,
    'Phone' : '0123456789'
}

new_row3 = {
    'Name' : "Bob",
    'Roll' : 4981,
    'Age' : 24,
    'Batch' : 'A',
    'CGPA' : 3.00,
    'Phone' : '0123456789'
}

In [138]:
# df.loc[len(df)] = row

df.loc[len(df)] = new_row1

In [139]:
df

      Name  Roll  Age Batch  CGPA       Phone
0  Monirul  3982   24     A  3.99  0123456789
1    Sayem  2981   25     B  4.00  0123456789
2   Hafiza  3973   22     C  3.87  0123456789
3      Mim  2973   21     D  2.78  0123456789
4    Sayem  2981   25     B  4.00  0123456789

In [140]:
# Inserting rows at index 3
new_record = pd.DataFrame([new_row2, new_row3])
df = pd.concat([df[:3], new_record, df[3:]]).reset_index(drop=True)
df

      Name  Roll  Age Batch  CGPA       Phone
0  Monirul  3982   24     A  3.99  0123456789
1    Sayem  2981   25     B  4.00  0123456789
2   Hafiza  3973   22     C  3.87  0123456789
3    Alice  2985   23     C  3.70  0123456789
4      Bob  4981   24     A  3.00  0123456789
5      Mim  2973   21     D  2.78  0123456789
6    Sayem  2981   25     B  4.00  0123456789