In [10]:
%run 02_Rows_&_Columns.ipynb
df=df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64
 2   Age     4 non-null      int64
 3   CGPA    4 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 260.0+ bytes

In [11]:
df

      Name  Roll  Age Batch  CGPA       Phone
0  Monirul  3982   24     A  3.99  0123456789
1    Sayem  2981   25     B  4.00  0123456789
2   Hafiza  3973   22     C  3.87  0123456789
3    Alice  2985   23     C  3.70  0123456789
4      Bob  4981   24     A  3.00  0123456789
5      Mim  2973   21     D  2.78  0123456789
6    Sayem  2981   25     B  4.00  0123456789

In [12]:
# Drop column


df.drop('Age', axis=1, inplace=True)  #axis = 1 (column)

In [13]:
df

      Name  Roll Batch  CGPA       Phone
0  Monirul  3982     A  3.99  0123456789
1    Sayem  2981     B  4.00  0123456789
2   Hafiza  3973     C  3.87  0123456789
3    Alice  2985     C  3.70  0123456789
4      Bob  4981     A  3.00  0123456789
5      Mim  2973     D  2.78  0123456789
6    Sayem  2981     B  4.00  0123456789

In [14]:
# Drop Row

df.drop(3, axis=0, inplace=True)  # axis = 0 (row)

In [15]:
df

      Name  Roll Batch  CGPA       Phone
0  Monirul  3982     A  3.99  0123456789
1    Sayem  2981     B  4.00  0123456789
2   Hafiza  3973     C  3.87  0123456789
4      Bob  4981     A  3.00  0123456789
5      Mim  2973     D  2.78  0123456789
6    Sayem  2981     B  4.00  0123456789

In [16]:
# reset the index
df.reset_index(drop=True, inplace=True)

df

      Name  Roll Batch  CGPA       Phone
0  Monirul  3982     A  3.99  0123456789
1    Sayem  2981     B  4.00  0123456789
2   Hafiza  3973     C  3.87  0123456789
3      Bob  4981     A  3.00  0123456789
4      Mim  2973     D  2.78  0123456789
5    Sayem  2981     B  4.00  0123456789

In [17]:
# Drop the duplicates

df.drop_duplicates(inplace=True) # removes one the rows if all values match


df

      Name  Roll Batch  CGPA       Phone
0  Monirul  3982     A  3.99  0123456789
1    Sayem  2981     B  4.00  0123456789
2   Hafiza  3973     C  3.87  0123456789
3      Bob  4981     A  3.00  0123456789
4      Mim  2973     D  2.78  0123456789

In [18]:
df.drop_duplicates(subset=['Batch'], inplace=True) # removes one of the rows, if 'Batch' matches


df

      Name  Roll Batch  CGPA       Phone
0  Monirul  3982     A  3.99  0123456789
1    Sayem  2981     B  4.00  0123456789
2   Hafiza  3973     C  3.87  0123456789
4      Mim  2973     D  2.78  0123456789