In [11]:
%run 04_Change_Value.ipynb
df = df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64
 2   Age     4 non-null      int64
 3   CGPA    4 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 260.0+ bytes

In [12]:
df = df.sort_values(by=['CGPA'], ascending=False)
df.reset_index(drop=True, inplace=True)


df

      Name  Roll Batch  CGPA     Contact
0    Sayem  2981     B  4.00  0123456789
1  Monirul  3982     A  3.99  0123456789
2   Hafiza  3973     C  3.87  0123456789
3     Tony  2973     D  2.78  0123456789

In [13]:
df[df['CGPA']>3.75]

      Name  Roll Batch  CGPA     Contact
0    Sayem  2981     B  4.00  0123456789
1  Monirul  3982     A  3.99  0123456789
2   Hafiza  3973     C  3.87  0123456789