In [915]:
import pandas as pd
from functools import reduce

In [916]:
# Importing all the csv files

try:
    scopus_all = pd.read_csv("ScopusAll.csv")
    scopus = pd.read_csv("Scopus.csv")
    science_direct = pd.read_csv("ScienceDirect.csv")
    springer = pd.read_csv("Springer.csv")
    ieee_all = pd.read_csv("IEEEXploreAll.csv")
    ieee_selected = pd.read_csv("IEEEXploreSelected.csv")
except Exception as e:
    print(e)
else:
    print("Imported all files!")

Imported all files!

In [917]:
# Viewing the Column info

In [918]:
scopus_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   115 non-null    object
 1   Year    115 non-null    int64
 2   DOI     115 non-null    object
 3   Link    115 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.7+ KB

In [919]:
scopus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Authors            47 non-null     object
 1   Author full names  47 non-null     object
 2   Author(s) ID       47 non-null     object
 3   Title              47 non-null     object
 4   Year               47 non-null     int64
 5   Link               47 non-null     object
 6   Abstract           47 non-null     object
 7   Publisher          47 non-null     object
dtypes: int64(1), object(7)
memory usage: 3.1+ KB

In [920]:
science_direct.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    59 non-null     object
 1   journal  59 non-null     object
 2   volume   59 non-null     int64
 3   number   6 non-null      float64
 4   pages    53 non-null     object
 5   year     59 non-null     int64
 6   issn     55 non-null     object
 7   doi      59 non-null     object
 8   url      59 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 4.3+ KB

In [921]:
science_direct.rename(columns={
    "title":"Title",
    "year":"Year",
    "doi":"DOI"
}, inplace=True)

science_direct.columns

Index(['Title', 'journal', 'volume', 'number', 'pages', 'Year', 'issn', 'DOI',
       'url'],
      dtype='object')

In [922]:
springer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Item Title         15 non-null     object
 1   Relevance          1 non-null      object
 2   Publication Title  15 non-null     object
 3   Book Series Title  0 non-null      float64
 4   Journal Volume     0 non-null      float64
 5   Journal Issue      0 non-null      float64
 6   Item DOI           15 non-null     object
 7   Authors            15 non-null     object
 8   Publication Year   15 non-null     int64
 9   URL                15 non-null     object
 10  Content Type       15 non-null     object
dtypes: float64(3), int64(1), object(7)
memory usage: 1.4+ KB

In [923]:
springer.rename(columns={
    "Item Title":"Title",
    "Publication Year":"Year",
    "Item DOI":"DOI"
}, inplace=True)

springer.columns

Index(['Title', 'Relevance', 'Publication Title', 'Book Series Title',
       'Journal Volume', 'Journal Issue', 'DOI', 'Authors', 'Year', 'URL',
       'Content Type'],
      dtype='object')

In [924]:
ieee_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Document Title          83 non-null     object
 1   Authors                 83 non-null     object
 2   Author Affiliations     83 non-null     object
 3   Publication Title       83 non-null     object
 4   Date Added To Xplore    83 non-null     object
 5   Publication Year        83 non-null     int64
 6   Volume                  62 non-null     float64
 7   Issue                   19 non-null     float64
 8   Start Page              83 non-null     int64
 9   End Page                83 non-null     int64
 10  Abstract                83 non-null     object
 11  ISSN                    73 non-null     object
 12  ISBNs                   21 non-null     object
 13  DOI                     83 non-null     object
 14  Funding Information     62 non-null     object
 15  PDF Link                83 non-null     object
 16  Author Keywords         77 non-null     object
 17  IEEE Terms              83 non-null     object
 18  Mesh_Terms              11 non-null     object
 19  Article Citation Count  75 non-null     float64
 20  Patent Citation Count   1 non-null      float64
 21  Reference Count         83 non-null     int64
 22  License                 83 non-null     object
 23  Online Date             83 non-null     object
 24  Issue Date              83 non-null     object
 25  Meeting Date            21 non-null     object
 26  Publisher               83 non-null     object
 27  Document Identifier     83 non-null     object
dtypes: float64(4), int64(4), object(20)
memory usage: 18.3+ KB

In [925]:
ieee_all.rename(columns={"Document Title": "Title", "Publication Year":"Year"}, inplace=True)
ieee_all.columns

Index(['Title', 'Authors', 'Author Affiliations', 'Publication Title',
       'Date Added To Xplore', 'Year', 'Volume', 'Issue', 'Start Page',
       'End Page', 'Abstract', 'ISSN', 'ISBNs', 'DOI', 'Funding Information',
       'PDF Link', 'Author Keywords', 'IEEE Terms', 'Mesh_Terms',
       'Article Citation Count', 'Patent Citation Count', 'Reference Count',
       'License', 'Online Date', 'Issue Date', 'Meeting Date', 'Publisher',
       'Document Identifier'],
      dtype='object')

In [926]:
ieee_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        9 non-null      object
 1   Unnamed: 1   9 non-null      object
 2   Unnamed: 2   9 non-null      object
 3   Unnamed: 3   9 non-null      object
 4   Unnamed: 4   9 non-null      object
 5   Year         9 non-null      int64
 6   Unnamed: 6   5 non-null      float64
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   9 non-null      int64
 9   Unnamed: 9   9 non-null      int64
 10  abstract     9 non-null      object
 11  Unnamed: 11  7 non-null      object
 12  Unnamed: 12  4 non-null      object
 13  Unnamed: 13  9 non-null      object
 14  Unnamed: 14  5 non-null      object
 15  Unnamed: 15  9 non-null      object
 16  Unnamed: 16  9 non-null      object
 17  Unnamed: 17  9 non-null      object
 18  Unnamed: 18  0 non-null      float64
 19  Unnamed: 19  5 non-null      float64
 20  Unnamed: 20  0 non-null      float64
 21  Unnamed: 21  9 non-null      int64
 22  Unnamed: 22  9 non-null      object
 23  Unnamed: 23  9 non-null      object
 24  Unnamed: 24  9 non-null      object
 25  Unnamed: 25  4 non-null      object
 26  Unnamed: 26  9 non-null      object
 27  Unnamed: 27  9 non-null      object
dtypes: float64(5), int64(4), object(19)
memory usage: 2.1+ KB

In [927]:
# Filtering ScopusAll according to Scopus's Title

In [928]:
# converting the title into a list

scopus_title = scopus['Title'].to_list()
len(scopus_title)

47

In [929]:
# Filtering ScopusAll

scopus_filtered = scopus_all[scopus_all['Title'].isin(scopus_title)].reset_index(drop=True)
len(scopus_filtered)

47

In [930]:
# Droping the columns except Title, Year, DOI

scopus_filtered = scopus_filtered[['Title', 'Year', 'DOI']]
scopus_filtered.columns

Index(['Title', 'Year', 'DOI'], dtype='object')

In [931]:
# Converting the DataFrame into CSV File

scopus_filtered.to_csv("ScopusFiltered.csv", index=False)

In [932]:
# Filtering the IEEEXploreAll according to the IEEEXploreSelected's title

In [933]:
# Converting the titles into a list

ieee_title = ieee_selected['title'].to_list()
ieee_title

['Comparing Abstract and Realistic Agent-Led Instructions for Language Learning in Virtual Environments: A Study on Presence Effects',
 'Advancing Engineering Education Through Serious Games: A Systematic Literature Review of Technological Innovation, Challenges, and Future Directions',
 'Design and Implementation of Metaverse for a Self-Learning Platform: a Case Study in KMUTNB Techno Park',
 'Impact of Different UI on Foreign Language Learning Using iVR',
 'Learning a Foreign Language: Traditional Listening vs Interactive Immersive Virtual Reality',
 'Improving Higher Education With the Use of Mobile Augmented Reality (MAR): A Case Study',
 'Interactive Augmented Reality System for Learning Phonetics Using Artificial Intelligence',
 'Teaching EFL With Immersive Virtual Reality Technologies: A Comparison With the Conventional Listening Method',
 'Game-based learning using a 3D virtual world in computer engineering education']

In [934]:
len(ieee_title)

9

In [935]:
# Filtering the IEEEXploreAll based on the created list

ieee_filtered = ieee_all[ieee_all['Title'].isin(ieee_title)].reset_index(drop=True)
ieee_filtered.count()   # got 9 papers

Title                     9
Authors                   9
Author Affiliations       9
Publication Title         9
Date Added To Xplore      9
Year                      9
Volume                    5
Issue                     0
Start Page                9
End Page                  9
Abstract                  9
ISSN                      7
ISBNs                     4
DOI                       9
Funding Information       5
PDF Link                  9
Author Keywords           9
IEEE Terms                9
Mesh_Terms                0
Article Citation Count    5
Patent Citation Count     0
Reference Count           9
License                   9
Online Date               9
Issue Date                9
Meeting Date              4
Publisher                 9
Document Identifier       9
dtype: int64

In [936]:
# Droping all the columns except the Title, Year, and DOI

ieee_filtered = ieee_filtered[['Title', 'Year', 'DOI']]
ieee_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   9 non-null      object
 1   Year    9 non-null      int64
 2   DOI     9 non-null      object
dtypes: int64(1), object(2)
memory usage: 348.0+ bytes

In [937]:
# Converting the DataFrame into a CSV file

ieee_filtered.to_csv("IEEEXploreFiltered.csv", index=False)

In [938]:
# Importing the newly created CSV file

try:
    scopus_filtered = pd.read_csv("ScopusFiltered.csv")
    ieee_filtered = pd.read_csv("IEEEXploreFiltered.csv")
except Exception as e:
    print(e)
else:
    print("Files Imported")

Files Imported

In [939]:
# Adding a new column named: Database

scopus_filtered['Database']='Scopus'
science_direct['Database']='ScienceDirect'
springer['Database']='Springer'
ieee_filtered['Database']='IEEEXplore'

In [940]:
# Calculating the number of papers

print(f"Scopus = {len(scopus_filtered)}")
print(f"ScienceDirect = {len(science_direct)}")
print(f"Springer = {len(springer)}")
print(f"IEEEXplore = {len(ieee_filtered)}")
print(f"Total = {len(scopus_filtered)+len(science_direct)+len(springer)+len(ieee_filtered)}")

Scopus = 47
ScienceDirect = 59
Springer = 15
IEEEXplore = 9
Total = 130

In [941]:
# Merging the files into one dataFrame

cols = ['Title', 'Year', 'DOI', 'Database']
dfs = [scopus_filtered[cols], science_direct[cols], springer[cols], ieee_filtered[cols]]

df = reduce(
    lambda x, y: pd.merge(
        x, y, on=cols, how='outer'
    ),
    dfs
)

len(df)

130

In [ ]:
# Removing the duplicates

df.drop_duplicates(subset=['Title'], inplace=True)
df.reset_index(drop=True, inplace=True)
df

,Title,Year,DOI,Database
0,A Comprehensive Multicomponent Neurosurgical C...,2021,https://doi.org/10.1016/j.jsurg.2020.11.003,ScienceDirect
1,A Systematic Overview of Reviews of the Use of...,2023,10.18870/hlrc.v13i2.1430,Scopus
2,A teaching design of ecological class based on...,2022,10.3389/fpsyg.2022.874101,Scopus
3,ADOPTION AND USAGE OF AUGMENTED REALITY-BASED ...,2024,10.28945/5351,Scopus
4,AR Tunnel: An augmented-reality digital twin f...,2026,https://doi.org/10.1016/j.cexr.2026.100139,ScienceDirect
...,...,...,...,...
122,Virtual reality for gender microaggression tra...,2026,https://doi.org/10.1016/j.cexr.2026.100149,ScienceDirect
123,Virtual reality in education: The impact of hi...,2023,https://doi.org/10.1016/j.cexr.2023.100020,ScienceDirect
124,Virtual reality in midwifery education: A mixe...,2022,https://doi.org/10.1016/j.nedt.2022.105573,ScienceDirect
125,What variables are connected with system usabi...,2023,https://doi.org/10.1016/j.cexr.2023.100043,ScienceDirect
126,“Case By Case”: Investigating the Use of a VR-...,2024,10.3390/virtualworlds3030019,Scopus

In [ ]:
# Calculating the length of the merges file

print(f"Total Papers (After removing the duplicates): {len(df)}")

Total Papers (After removing the duplicates): 127

In [ ]:
# Checking the number of papers from 2022-2026

print(f"Papers from the last 5 years: {len(df[df['Year']>2021])}")

Papers from the last 5 years: 102

In [ ]:
# Removing the papers before 2022

df = df[df['Year']>=2022].reset_index(drop=True)
df

,Title,Year,DOI,Database
0,A Systematic Overview of Reviews of the Use of...,2023,10.18870/hlrc.v13i2.1430,Scopus
1,A teaching design of ecological class based on...,2022,10.3389/fpsyg.2022.874101,Scopus
2,ADOPTION AND USAGE OF AUGMENTED REALITY-BASED ...,2024,10.28945/5351,Scopus
3,AR Tunnel: An augmented-reality digital twin f...,2026,https://doi.org/10.1016/j.cexr.2026.100139,ScienceDirect
4,Advancing Engineering Education Through Seriou...,2026,10.1109/ACCESS.2026.3669416,IEEEXplore
...,...,...,...,...
97,Virtual reality for gender microaggression tra...,2026,https://doi.org/10.1016/j.cexr.2026.100149,ScienceDirect
98,Virtual reality in education: The impact of hi...,2023,https://doi.org/10.1016/j.cexr.2023.100020,ScienceDirect
99,Virtual reality in midwifery education: A mixe...,2022,https://doi.org/10.1016/j.nedt.2022.105573,ScienceDirect
100,What variables are connected with system usabi...,2023,https://doi.org/10.1016/j.cexr.2023.100043,ScienceDirect
101,“Case By Case”: Investigating the Use of a VR-...,2024,10.3390/virtualworlds3030019,Scopus

In [ ]:
# Sorting the papers based on 'Database', and 'Year'

df = df.sort_values(by=['Database', 'Year'], ascending=False).reset_index(drop=True)

In [947]:
df

,Title,Year,DOI,Database
0,Flight simulator with hardware and virtual rea...,2026,10.1007/s44217-026-01702-8,Springer
1,Design of generative AI-powered pedagogy for v...,2025,10.1038/s41539-025-00326-1,Springer
2,Effectiveness of Augmented Reality and Virtual...,2025,10.1007/s11528-025-01106-9,Springer
3,Flipped and Immersive Student Learning Strateg...,2025,10.1007/s11528-025-01122-9,Springer
4,From adoption to social sustainability: examin...,2025,10.1007/s10639-025-13720-4,Springer
...,...,...,...,...
97,Impact of Different UI on Foreign Language Lea...,2024,10.1109/ICGI64003.2024.10923812,IEEEXplore
98,Improving Higher Education With the Use of Mob...,2024,10.1109/ACCESS.2024.3465833,IEEEXplore
99,Interactive Augmented Reality System for Learn...,2024,10.1109/ACCESS.2024.3406494,IEEEXplore
100,Learning a Foreign Language: Traditional Liste...,2024,10.1109/ICGI64003.2024.10923758,IEEEXplore
101,Teaching EFL With Immersive Virtual Reality Te...,2023,10.1109/ACCESS.2023.3249578,IEEEXplore