In [1]:
%run 01_initialization.ipynb
df=df

CSV File Imported!

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No         151 non-null    int64
 1   Name       151 non-null    object
 2   Type1      151 non-null    object
 3   Type2      67 non-null     object
 4   Height     146 non-null    float64
 5   Weight     146 non-null    float64
 6   Legendary  151 non-null    int64
dtypes: float64(2), int64(2), object(3)
memory usage: 8.4+ KB

In [4]:
df.head()

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0     NaN          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     NaN     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0

In [5]:
df.tail()

      No       Name    Type1   Type2  Height  Weight  Legendary
146  147    Dratini   Dragon     NaN     1.8     3.3          0
147  148  Dragonair   Dragon     NaN     4.0    16.5          0
148  149  Dragonite   Dragon  Flying     2.2   210.0          0
149  150     Mewtwo  Psychic     NaN     2.0   122.0          1
150  150     Mewtwo  Psychic     NaN     2.0   122.0          1

In [6]:
df.count()

No           151
Name         151
Type1        151
Type2         67
Height       146
Weight       146
Legendary    151
dtype: int64

In [7]:
len(df)

151

In [8]:
df.columns

Index(['No', 'Name', 'Type1', 'Type2', 'Height', 'Weight', 'Legendary'], dtype='object')