In [45]:
%run 02_File_Reading.ipynb
df = df

CSV File Imported!
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No         151 non-null    int64
 1   Name       151 non-null    object
 2   Type1      151 non-null    object
 3   Type2      67 non-null     object
 4   Height     146 non-null    float64
 5   Weight     146 non-null    float64
 6   Legendary  151 non-null    int64
dtypes: float64(2), int64(2), object(3)
memory usage: 8.4+ KB

In [46]:
df['Name']

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
146       Dratini
147     Dragonair
148     Dragonite
149        Mewtwo
150        Mewtwo
Name: Name, Length: 151, dtype: object

In [47]:
df[df['Name']=='Dratini']

      No     Name   Type1 Type2  Height  Weight  Legendary
146  147  Dratini  Dragon   NaN     1.8     3.3          0

In [48]:
tall = df[df['Height']>2.0]
tall

      No        Name   Type1   Type2  Height  Weight  Legendary
94    95        Onix    Rock  Ground     8.8   210.0          0
114  115  Kangaskhan  Normal     NaN     2.2    80.0          0
129  130    Gyarados   Water  Flying     6.5   235.0          0
130  131      Lapras   Water     Ice     2.5   220.0          0
142  143     Snorlax  Normal     NaN     2.1   460.0          0
147  148   Dragonair  Dragon     NaN     4.0    16.5          0
148  149   Dragonite  Dragon  Flying     2.2   210.0          0

In [49]:
tall = tall.sort_values(by=['Height'], ascending=False)
tall

      No        Name   Type1   Type2  Height  Weight  Legendary
94    95        Onix    Rock  Ground     8.8   210.0          0
129  130    Gyarados   Water  Flying     6.5   235.0          0
147  148   Dragonair  Dragon     NaN     4.0    16.5          0
130  131      Lapras   Water     Ice     2.5   220.0          0
114  115  Kangaskhan  Normal     NaN     2.2    80.0          0
148  149   Dragonite  Dragon  Flying     2.2   210.0          0
142  143     Snorlax  Normal     NaN     2.1   460.0          0