In [584]:
import pandas as pd
import numpy as np

In [585]:
try:
    df = pd.read_csv('../data.csv')
except Exception as e:
    print(e)
else:
    print('CSV File Imported!')

CSV File Imported!

In [586]:
df.head()

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0     NaN          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     NaN     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0

In [587]:
df.isnull() # returns True for nan value

        No   Name  Type1  Type2  Height  Weight  Legendary
0    False  False  False  False   False   False      False
1    False  False  False  False   False    True      False
2    False  False  False  False   False   False      False
3    False  False  False   True    True   False      False
4    False  False  False   True   False   False      False
..     ...    ...    ...    ...     ...     ...        ...
146  False  False  False   True   False   False      False
147  False  False  False   True   False   False      False
148  False  False  False  False   False   False      False
149  False  False  False   True   False   False      False
150  False  False  False   True   False   False      False

[151 rows x 7 columns]

In [588]:
print(df.isnull().sum()) # sum of missing value in each column

No            0
Name          0
Type1         0
Type2        84
Height        5
Weight        5
Legendary     0
dtype: int64

In [589]:
# print(df.isnull().sum()) shows that the column Type2, and Weight has null value

In [590]:
df['Weight'].fillna(round(df['Weight'].mean(), 2), inplace=True)
df

C:\Users\Hp\AppData\Local\Temp\ipykernel_8340\2550994568.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Weight'].fillna(round(df['Weight'].mean(), 2), inplace=True)

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7    6.90          0
1      2     Ivysaur    Grass  Poison     1.0   47.79          0
2      3    Venusaur    Grass  Poison     2.0  100.00          0
3      4  Charmander     Fire     NaN     NaN    8.50          0
4      5  Charmeleon     Fire     NaN     1.1   19.00          0
..   ...         ...      ...     ...     ...     ...        ...
146  147     Dratini   Dragon     NaN     1.8    3.30          0
147  148   Dragonair   Dragon     NaN     4.0   16.50          0
148  149   Dragonite   Dragon  Flying     2.2  210.00          0
149  150      Mewtwo  Psychic     NaN     2.0  122.00          1
150  150      Mewtwo  Psychic     NaN     2.0  122.00          1

[151 rows x 7 columns]

In [591]:
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7    6.90          0
1      2     Ivysaur    Grass  Poison     1.0   47.79          0
2      3    Venusaur    Grass  Poison     2.0  100.00          0
3      4  Charmander     Fire     NaN     NaN    8.50          0
4      5  Charmeleon     Fire     NaN     1.1   19.00          0
..   ...         ...      ...     ...     ...     ...        ...
146  147     Dratini   Dragon     NaN     1.8    3.30          0
147  148   Dragonair   Dragon     NaN     4.0   16.50          0
148  149   Dragonite   Dragon  Flying     2.2  210.00          0
149  150      Mewtwo  Psychic     NaN     2.0  122.00          1
150  150      Mewtwo  Psychic     NaN     2.0  122.00          1

[151 rows x 7 columns]

In [592]:
df['Height'].fillna(round(df['Height'].mean(), 2), inplace=True)

C:\Users\Hp\AppData\Local\Temp\ipykernel_8340\1300914232.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Height'].fillna(round(df['Height'].mean(), 2), inplace=True)

In [593]:
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7    6.90          0
1      2     Ivysaur    Grass  Poison     1.0   47.79          0
2      3    Venusaur    Grass  Poison     2.0  100.00          0
3      4  Charmander     Fire     NaN     1.2    8.50          0
4      5  Charmeleon     Fire     NaN     1.1   19.00          0
..   ...         ...      ...     ...     ...     ...        ...
146  147     Dratini   Dragon     NaN     1.8    3.30          0
147  148   Dragonair   Dragon     NaN     4.0   16.50          0
148  149   Dragonite   Dragon  Flying     2.2  210.00          0
149  150      Mewtwo  Psychic     NaN     2.0  122.00          1
150  150      Mewtwo  Psychic     NaN     2.0  122.00          1

[151 rows x 7 columns]

In [594]:
df.drop_duplicates(inplace=True) # it drops the duplicates

In [595]:
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7    6.90          0
1      2     Ivysaur    Grass  Poison     1.0   47.79          0
2      3    Venusaur    Grass  Poison     2.0  100.00          0
3      4  Charmander     Fire     NaN     1.2    8.50          0
4      5  Charmeleon     Fire     NaN     1.1   19.00          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0   60.00          1
146  147     Dratini   Dragon     NaN     1.8    3.30          0
147  148   Dragonair   Dragon     NaN     4.0   16.50          0
148  149   Dragonite   Dragon  Flying     2.2  210.00          0
149  150      Mewtwo  Psychic     NaN     2.0  122.00          1

[150 rows x 7 columns]

In [596]:
# Check whether there are any negative values

In [597]:
n_df = df.select_dtypes(include='number')
(n_df<0).sum()

No           0
Height       0
Weight       2
Legendary    0
dtype: int64

In [598]:
df['Weight'] = np.where(df['Weight']>=0, df['Weight'], round(df['Weight'].mean(), 2))
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7    6.90          0
1      2     Ivysaur     Grass    Poison     1.0   47.79          0
2      3    Venusaur     Grass    Poison     2.0  100.00          0
3      4  Charmander      Fire       NaN     1.2    8.50          0
4      5  Charmeleon      Fire       NaN     1.1   19.00          0
5      6   Charizard      Fire    Flying     1.7   90.50          0
6      7    Squirtle     Water       NaN     0.5    9.00          0
7      8   Wartortle     Water       NaN     1.0   47.79          0
8      9   Blastoise     Water       NaN     1.2   85.50          0
9     10    Caterpie       Bug       NaN     0.3    2.90          0
10    11     Metapod       Bug       NaN     0.7   47.79          0
11    12  Butterfree       Bug    Flying     1.1   32.00          0
12    13      Weedle       Bug    Poison     0.3   47.79          0
13    14      Kakuna       Bug    Poison     0.6   10.00          0
14    15    Beedrill       Bug    Poison     1.0   29.50          0
15    16      Pidgey    Normal    Flying     0.3   47.30          0
16    17   Pidgeotto    Normal    Flying     1.1   30.00          0
17    18     Pidgeot    Normal    Flying     1.5   39.50          0
18    19     Rattata    Normal       NaN     1.2   47.30          0
19    20    Raticate    Normal       NaN     0.7   18.50          0
20    21     Spearow    Normal    Flying     0.3    2.00          0
21    22      Fearow    Normal    Flying     1.2   38.00          0
22    23       Ekans    Poison       NaN     2.0    6.90          0
23    24       Arbok    Poison       NaN     1.2   65.00          0
24    25     Pikachu  Electric       NaN     0.4    6.00          0
25    26      Raichu  Electric       NaN     0.8   30.00          0
26    27   Sandshrew    Ground       NaN     0.6   12.00          0
27    28   Sandslash    Ground       NaN     1.0   29.50          0
28    29    Nidoran♀    Poison       NaN     0.4    7.00          0
29    30    Nidorina    Poison       NaN     0.8   47.79          0
30    31   Nidoqueen    Poison    Ground     1.3   60.00          0
31    32    Nidoran♂    Poison       NaN     0.5    9.00          0
32    33    Nidorino    Poison       NaN     0.9   19.50          0
33    34    Nidoking    Poison    Ground     1.4   62.00          0
34    35    Clefairy     Fairy       NaN     1.2    7.50          0
35    36    Clefable     Fairy       NaN     1.3   40.00          0
36    37      Vulpix      Fire       NaN     0.6    9.90          0
37    38   Ninetales      Fire       NaN     1.1   19.90          0
38    39  Jigglypuff    Normal     Fairy     0.5    5.50          0
39    40  Wigglytuff    Normal     Fairy     1.0   12.00          0
40    41       Zubat    Poison    Flying     0.8    7.50          0
41    42      Golbat    Poison    Flying     1.6   55.00          0
42    43      Oddish     Grass    Poison     0.5    5.40          0
43    44       Gloom     Grass    Poison     0.8    8.60          0
44    45   Vileplume     Grass    Poison     1.2   18.60          0
45    46       Paras       Bug     Grass     0.3    5.40          0
46    47    Parasect       Bug     Grass     1.0   29.50          0
47    48     Venonat       Bug    Poison     1.0   30.00          0
48    49    Venomoth       Bug    Poison     1.5   12.50          0
49    50     Diglett    Ground       NaN     0.2    0.80          0
50    51     Dugtrio    Ground       NaN     0.7   33.30          0
51    52      Meowth    Normal       NaN     0.4    4.20          0
52    53     Persian    Normal       NaN     1.0   32.00          0
53    54     Psyduck     Water       NaN     0.8   19.60          0
54    55     Golduck     Water       NaN     1.7   76.60          0
55    56      Mankey  Fighting       NaN     0.5   28.00          0
56    57    Primeape  Fighting       NaN     1.0   32.00          0
57    58   Growlithe      Fire       NaN     0.7   19.00          0
58    59    Arcanine      Fire       NaN     1.9  155.00          0
59    60     Poliwag     Water       NaN     0.6   12.40          0
60    61   Poliwhirl     Water       NaN     1.0   20.00          0
61    62   Poliwrath     Water  Fighting     1.3   54.00          0
62    63        Abra   Psychic       NaN     0.9   19.50          0
63    64     Kadabra   Psychic       NaN     1.3   56.50          0
64    65    Alakazam   Psychic       NaN     1.5   48.00          0
65    66      Machop  Fighting       NaN     0.8   19.50          0
66    67     Machoke  Fighting       NaN     1.5   70.50          0
67    68     Machamp  Fighting       NaN     1.6  130.00          0
68    69  Bellsprout     Grass    Poison     0.7    4.00          0
69    70  Weepinbell     Grass    Poison     1.0    6.40          0
70    71  Victreebel     Grass    Poison     1.7   15.50          0
71    72   Tentacool     Water    Poison     0.9   45.50          0
72    73  Tentacruel     Water    Poison     1.6   55.00          0
73    74     Geodude      Rock    Ground     0.4   20.00          0
74    75    Graveler      Rock    Ground     1.0  105.00          0
75    76       Golem      Rock    Ground     1.4  300.00          0
76    77      Ponyta      Fire       NaN     1.0   30.00          0
77    78    Rapidash      Fire       NaN     1.7   95.00          0
78    79    Slowpoke     Water   Psychic     1.2   36.00          0
79    80     Slowbro     Water   Psychic     1.6   78.50          0
80    81   Magnemite  Electric     Steel     0.3    6.00          0
81    82    Magneton  Electric     Steel     1.0   60.00          0
82    83  Farfetch'd    Normal    Flying     0.8   15.00          0
83    84       Doduo    Normal    Flying     1.4   39.20          0
84    85      Dodrio    Normal    Flying     1.8   85.20          0
85    86        Seel     Water       NaN     1.1   90.00          0
86    87     Dewgong     Water       Ice     1.7  120.00          0
87    88      Grimer    Poison       NaN     0.9   30.00          0
88    89         Muk    Poison       NaN     1.2   30.00          0
89    90    Shellder     Water       NaN     0.3    4.00          0
90    91    Cloyster     Water       Ice     1.5  132.50          0
91    92      Gastly     Ghost    Poison     1.3    0.10          0
92    93     Haunter     Ghost    Poison     1.6    0.10          0
93    94      Gengar     Ghost    Poison     1.5   40.50          0
94    95        Onix      Rock    Ground     8.8  210.00          0
95    96     Drowzee   Psychic       NaN     1.0   32.40          0
96    97       Hypno   Psychic       NaN     1.6   75.60          0
97    98      Krabby     Water       NaN     0.4    6.50          0
98    99     Kingler     Water       NaN     1.3   60.00          0
99   100     Voltorb  Electric       NaN     0.5   10.40          0
100  101   Electrode  Electric       NaN     1.2   66.60          0
101  102   Exeggcute     Grass   Psychic     0.4    2.50          0
102  103   Exeggutor     Grass   Psychic     2.0  120.00          0
103  104      Cubone    Ground       NaN     0.4    6.50          0
104  105     Marowak    Ground       NaN     1.0   45.00          0
105  106   Hitmonlee  Fighting       NaN     1.5   49.80          0
106  107  Hitmonchan  Fighting       NaN     1.4   50.20          0
107  108   Lickitung    Normal       NaN     1.2   65.50          0
108  109     Koffing    Poison       NaN     0.6    1.00          0
109  110     Weezing    Poison       NaN     1.2    9.50          0
110  111     Rhyhorn    Ground      Rock     1.0  115.00          0
111  112      Rhydon    Ground      Rock     1.9  120.00          0
112  113     Chansey    Normal       NaN     1.1   34.60          0
113  114     Tangela     Grass       NaN     1.0   35.00          0
114  115  Kangaskhan    Normal       NaN     2.2   80.00          0
115  116      Horsea     Water       NaN     0.4    8.00          0
116  117      Seadra     Water       NaN     1.2   25.00          0
117  118     Goldeen     Water       NaN     0.6   15.00          0
118  119     Seaking     Water       NaN     1.3   39.00          0
119  120      Staryu     Water       NaN     0.8   34.50          0
120  121     Starmie     Water   Psychic     1.1   80.00          0
121  122    Mr. Mime   Psychic     Fairy     1.3   54.50          0
122  123     Scyther       Bug    Flying     1.5   56.00          0
123  124        Jynx       Ice   Psychic     1.4   40.60          0
124  125  Electabuzz  Electric       NaN     1.1   30.00          0
125  126      Magmar      Fire       NaN     1.3   44.50          0
126  127      Pinsir       Bug       NaN     1.5   55.00          0
127  128      Tauros    Normal       NaN     1.4   88.40          0
128  129    Magikarp     Water       NaN     0.9   10.00          0
129  130    Gyarados     Water    Flying     6.5  235.00          0
130  131      Lapras     Water       Ice     2.5  220.00          0
131  132       Ditto    Normal       NaN     0.3    4.00          0
132  133       Eevee    Normal       NaN     0.3    6.50          0
133  134    Vaporeon     Water       NaN     1.0   29.00          0
134  135     Jolteon  Electric       NaN     0.8   24.50          0
135  136     Flareon      Fire       NaN     0.9   25.00          0
136  137     Porygon    Normal       NaN     0.8   36.50          0
137  138     Omanyte      Rock     Water     0.4    7.50          0
138  139     Omastar      Rock     Water     1.0   35.00          0
139  140      Kabuto      Rock     Water     0.5   11.50          0
140  141    Kabutops      Rock     Water     1.3   40.50          0
141  142  Aerodactyl      Rock    Flying     1.8   59.00          0
142  143     Snorlax    Normal       NaN     2.1  460.00          0
143  144    Articuno       Ice    Flying     1.7   55.40          1
144  145      Zapdos  Electric    Flying     1.6   52.60          1
145  146     Moltres      Fire    Flying     2.0   60.00          1
146  147     Dratini    Dragon       NaN     1.8    3.30          0
147  148   Dragonair    Dragon       NaN     4.0   16.50          0
148  149   Dragonite    Dragon    Flying     2.2  210.00          0
149  150      Mewtwo   Psychic       NaN     2.0  122.00          1

In [599]:
df['Weight'].idxmin(), df['Weight'].idxmax()

(np.int64(91), np.int64(142))

In [600]:
df.iloc[91]

No               92
Name         Gastly
Type1         Ghost
Type2        Poison
Height          1.3
Weight          0.1
Legendary         0
Name: 91, dtype: object

In [601]:
df.iloc[142]

No               143
Name         Snorlax
Type1         Normal
Type2            NaN
Height           2.1
Weight         460.0
Legendary          0
Name: 142, dtype: object

In [602]:
meanVal = df['Weight'].mean()
stdVal = df['Weight'].std()
lowerBound = meanVal - (3*stdVal)
upperBound = meanVal + (3*stdVal)

In [603]:
print(f"Lower Bound: {lowerBound} and Upper Bound: {upperBound}")

Lower Bound: -129.02170320365542 and Upper Bound: 224.9463698703221

In [604]:
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7    6.90          0
1      2     Ivysaur    Grass  Poison     1.0   47.79          0
2      3    Venusaur    Grass  Poison     2.0  100.00          0
3      4  Charmander     Fire     NaN     1.2    8.50          0
4      5  Charmeleon     Fire     NaN     1.1   19.00          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0   60.00          1
146  147     Dratini   Dragon     NaN     1.8    3.30          0
147  148   Dragonair   Dragon     NaN     4.0   16.50          0
148  149   Dragonite   Dragon  Flying     2.2  210.00          0
149  150      Mewtwo  Psychic     NaN     2.0  122.00          1

[150 rows x 7 columns]

In [605]:
df = df[(df['Weight'] >= lowerBound) & (df['Weight'] <= upperBound)]

# It removes all the rows whice has Weight less than lowerBound and greater than upperBound

In [606]:
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7    6.90          0
1      2     Ivysaur    Grass  Poison     1.0   47.79          0
2      3    Venusaur    Grass  Poison     2.0  100.00          0
3      4  Charmander     Fire     NaN     1.2    8.50          0
4      5  Charmeleon     Fire     NaN     1.1   19.00          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0   60.00          1
146  147     Dratini   Dragon     NaN     1.8    3.30          0
147  148   Dragonair   Dragon     NaN     4.0   16.50          0
148  149   Dragonite   Dragon  Flying     2.2  210.00          0
149  150      Mewtwo  Psychic     NaN     2.0  122.00          1

[147 rows x 7 columns]