In [60]:
# DataFrame = A  tabular data structure with rows AND columns (2-Dimensional)
# Similar to an Excel Spreadsheet

In [61]:
import pandas as pd

In [62]:
data = {
    "Name" : ['student 1', 'student 2', 'student 3', 'student 4', 'student 5'],
    "Age" : [21, 22, 20, 19, 23],
    "CGPA" : [3.95, 3.56, 4.00, 3.19, 3.82]
}
data # data is a dictionary of lists

{'Name': ['student 1', 'student 2', 'student 3', 'student 4', 'student 5'],
 'Age': [21, 22, 20, 19, 23],
 'CGPA': [3.95, 3.56, 4.0, 3.19, 3.82]}

In [63]:
df = pd.DataFrame(data, index=['s1', 's2', 's3', 's4', 's5'])
df

         Name  Age  CGPA
s1  student 1   21  3.95
s2  student 2   22  3.56
s3  student 3   20  4.00
s4  student 4   19  3.19
s5  student 5   23  3.82

In [64]:
df.loc['s2']

Name    student 2
Age            22
CGPA         3.56
Name: s2, dtype: object

In [65]:
df.iloc[1]

Name    student 2
Age            22
CGPA         3.56
Name: s2, dtype: object

In [66]:
df.iloc[2]

Name    student 3
Age            20
CGPA          4.0
Name: s3, dtype: object

In [67]:
# Add a new column
# df.insert(position, column_name, values)

df.insert(2, "Contact", ["01401411046", "01543543412", "01873123456", "01923123456", "01624123456"])
df

         Name  Age      Contact  CGPA
s1  student 1   21  01401411046  3.95
s2  student 2   22  01543543412  3.56
s3  student 3   20  01873123456  4.00
s4  student 4   19  01923123456  3.19
s5  student 5   23  01624123456  3.82

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, s1 to s5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      5 non-null      int64
 2   Contact  5 non-null      object
 3   CGPA     5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 372.0+ bytes

In [69]:
# Add a new row

new_row = pd.DataFrame([
        {'Name':'student 6', 'Age':24, 'CGPA':3.45, 'Contact':'01302123456'},
        {'Name':'student 7', 'Age':21, 'CGPA':3.23, 'Contact':'01670123456'},
        {'Name':'student 7', 'Age':21, 'CGPA':3.23, 'Contact':'01670123456'},
    ], index=['s6', 's7', 's8'])
df = pd.concat([df, new_row])
df

         Name  Age      Contact  CGPA
s1  student 1   21  01401411046  3.95
s2  student 2   22  01543543412  3.56
s3  student 3   20  01873123456  4.00
s4  student 4   19  01923123456  3.19
s5  student 5   23  01624123456  3.82
s6  student 6   24  01302123456  3.45
s7  student 7   21  01670123456  3.23
s8  student 7   21  01670123456  3.23

In [70]:
# Add a new row
# df.loc[index] = new_record

new_student = {
    "Name":"student 7",
    "Age":25,
    "CGPA":4.00,
    "Contact": "01234567891"
}

index = 's'+ str(len(df)+1)
df.loc[index] = new_student
df

         Name  Age      Contact  CGPA
s1  student 1   21  01401411046  3.95
s2  student 2   22  01543543412  3.56
s3  student 3   20  01873123456  4.00
s4  student 4   19  01923123456  3.19
s5  student 5   23  01624123456  3.82
s6  student 6   24  01302123456  3.45
s7  student 7   21  01670123456  3.23
s8  student 7   21  01670123456  3.23
s9  student 7   25  01234567891  4.00

In [71]:
# Row = axis 0
# Column = axis 1

In [72]:
# Remove a column
# df.drop("Column_name", axis=1, inplace=True)

df.drop("Age", axis=1, inplace=True)
df

         Name      Contact  CGPA
s1  student 1  01401411046  3.95
s2  student 2  01543543412  3.56
s3  student 3  01873123456  4.00
s4  student 4  01923123456  3.19
s5  student 5  01624123456  3.82
s6  student 6  01302123456  3.45
s7  student 7  01670123456  3.23
s8  student 7  01670123456  3.23
s9  student 7  01234567891  4.00

In [73]:
# Remove a row
# df.drop("row_index", axis=1, inplace=True)

df.drop('s1', axis=0, inplace=True)
df

         Name      Contact  CGPA
s2  student 2  01543543412  3.56
s3  student 3  01873123456  4.00
s4  student 4  01923123456  3.19
s5  student 5  01624123456  3.82
s6  student 6  01302123456  3.45
s7  student 7  01670123456  3.23
s8  student 7  01670123456  3.23
s9  student 7  01234567891  4.00

In [74]:
# Remove Duplicates

df.drop_duplicates(inplace=True)   # removes duplicates by comparing all the columns
df

         Name      Contact  CGPA
s2  student 2  01543543412  3.56
s3  student 3  01873123456  4.00
s4  student 4  01923123456  3.19
s5  student 5  01624123456  3.82
s6  student 6  01302123456  3.45
s7  student 7  01670123456  3.23
s9  student 7  01234567891  4.00

In [75]:
# Remove Duplicates

df.drop_duplicates(subset=["Name"])

         Name      Contact  CGPA
s2  student 2  01543543412  3.56
s3  student 3  01873123456  4.00
s4  student 4  01923123456  3.19
s5  student 5  01624123456  3.82
s6  student 6  01302123456  3.45
s7  student 7  01670123456  3.23

In [76]:
# Change a value

df.loc['s2', "CGPA"] = 2.50
df

         Name      Contact  CGPA
s2  student 2  01543543412  2.50
s3  student 3  01873123456  4.00
s4  student 4  01923123456  3.19
s5  student 5  01624123456  3.82
s6  student 6  01302123456  3.45
s7  student 7  01670123456  3.23
s9  student 7  01234567891  4.00

In [77]:
# Change the name of the Column
# df.rename(columns={"old_name": "new_name"}, inplace=True)

df.rename(columns={"Contact":"Phone"}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, s2 to s9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Phone   7 non-null      object
 2   CGPA    7 non-null      float64
dtypes: float64(1), object(2)
memory usage: 524.0+ bytes

In [78]:
# Sort DataFrame

df = df.sort_values(by="CGPA", ascending=False)
df

         Name        Phone  CGPA
s3  student 3  01873123456  4.00
s9  student 7  01234567891  4.00
s5  student 5  01624123456  3.82
s6  student 6  01302123456  3.45
s7  student 7  01670123456  3.23
s4  student 4  01923123456  3.19
s2  student 2  01543543412  2.50

In [79]:
df[df['CGPA']<3.50]

         Name        Phone  CGPA
s6  student 6  01302123456  3.45
s7  student 7  01670123456  3.23
s4  student 4  01923123456  3.19
s2  student 2  01543543412  2.50

In [80]:
# Convert the data into CSV File
df.to_csv('../students.csv', index=False)