In [1]:
# DataFrame = A  tabular data structure with rows AND columns (2-Dimensional)
# Similar to an Excel Spreadsheet

In [2]:
import pandas as pd

In [3]:
data = {
    "Name" : ['student 1', 'student 2', 'student 3', 'student 4', 'student 5'],
    "Age" : [21, 22, 20, 19, 23],
    "CGPA" : [3.95, 3.56, 4.00, 3.19, 3.82]
}
data # data is a dictionary of lists

{'Name': ['student 1', 'student 2', 'student 3', 'student 4', 'student 5'],
 'Age': [21, 22, 20, 19, 23],
 'CGPA': [3.95, 3.56, 4.0, 3.19, 3.82]}

In [4]:
df = pd.DataFrame(data, index=['s1', 's2', 's3', 's4', 's5'])
df

         Name  Age  CGPA
s1  student 1   21  3.95
s2  student 2   22  3.56
s3  student 3   20  4.00
s4  student 4   19  3.19
s5  student 5   23  3.82

In [5]:
df.loc['s2']

Name    student 2
Age            22
CGPA         3.56
Name: s2, dtype: object

In [6]:
df.iloc[1]

Name    student 2
Age            22
CGPA         3.56
Name: s2, dtype: object

In [7]:
df.iloc[2]

Name    student 3
Age            20
CGPA          4.0
Name: s3, dtype: object

In [8]:
# Add a new column

df['Contact'] = ['01401411046', '01543543412', '01873123456', '01923123456', '01624123456']
df

         Name  Age  CGPA      Contact
s1  student 1   21  3.95  01401411046
s2  student 2   22  3.56  01543543412
s3  student 3   20  4.00  01873123456
s4  student 4   19  3.19  01923123456
s5  student 5   23  3.82  01624123456

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, s1 to s5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      5 non-null      int64
 2   CGPA     5 non-null      float64
 3   Contact  5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 372.0+ bytes

In [10]:
# Add a new row

new_row = pd.DataFrame([
        {'Name':'student 6', 'Age':24, 'CGPA':3.45, 'Contact':'01302123456'},
        {'Name':'student 7', 'Age':21, 'CGPA':3.23, 'Contact':'01670123456'}
    ], index=['s6', 's7'])
df = pd.concat([df, new_row])
df

         Name  Age  CGPA      Contact
s1  student 1   21  3.95  01401411046
s2  student 2   22  3.56  01543543412
s3  student 3   20  4.00  01873123456
s4  student 4   19  3.19  01923123456
s5  student 5   23  3.82  01624123456
s6  student 6   24  3.45  01302123456
s7  student 7   21  3.23  01670123456

In [11]:
df[df['CGPA']<3.50]

         Name  Age  CGPA      Contact
s4  student 4   19  3.19  01923123456
s6  student 6   24  3.45  01302123456
s7  student 7   21  3.23  01670123456

In [12]:
# Convert the data into CSV File
df.to_csv('../students.csv', index=False)